# Rebuilds the ISOFIT `dev` branch results for the main branch of this PR-tests results repo

name: Dev

on:
  push:
    branches:
      - main
    paths-ignore:
      - "dev/**"
  workflow_dispatch:

jobs:
  extras:
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.25"
          python-version: "3.12"
          activate-environment: true

      - name: Install ISOFIT
        run: |
          uv add git+https://github.com/isofit/isofit --branch dev

      - name: Download Extras
        shell: bash
        run: |
          echo "Downloading extras"
          isofit download all
          echo "Building examples"
          isofit build

      - uses: actions/upload-artifact@v6
        with:
          name: extras
          path: ~/.isofit

  upload:
    # NOTE: Add other jobs here when adding a new workflow file
    needs:
      - imagecube-small
      - lakemary
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Prepare
        run: rm -rf dev

      - uses: actions/download-artifact@v8
        with:
          path: dev

      - name: Remove Extras
        run: rm -rf dev/extras

      - name: Commit and push results
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          file_pattern: 'dev/*'

  imagecube-small:
    needs: extras
    uses: ./.github/workflows/results_imagecube_small.yml

  # lakemary:
  #   needs: extras
  #   uses: ./.github/workflows/results_lakemary.yml
